

package IHMcoach;
import liguapoulpe.*;
import Reseaux.*;

import javax.swing.DefaultListModel;

/**
 *
 * @author Gus
 * Cette fenetre affiche les equipes aui sont deja creer et ici on attend pour
 * autres jouers
 */
public class CH_3_Lancerlacompetition extends javax.swing.JFrame {

    CH_4_TournoiPremierePhase CH4;
    TCP_SERVER myTCP;
    private String myIPadress, hostIPadress;
    private int port;
    Tournament t;
    int myNV;
    DefaultListModel ListModelTeam = new DefaultListModel();
    DefaultListModel ListModelCoach = new DefaultListModel();
    Coach [] nomCoach;

    /**
     *
     * Constructeur de la classe
     */
    public CH_3_Lancerlacompetition(String hostIPadress,int port,String myIPadress,TCP_SERVER myTCP) {

        super("Lancement du Tournoi");

        this.hostIPadress=hostIPadress;
        this.myTCP=myTCP;
        this.myIPadress=myIPadress;
        this.port=port;

        initComponents();
        this.setSize(800, 600);
        this.setResizable(false);
        this.setVisible(true);
        this.t = myTCP.getTournament();
        nomCoach = t.getCoach();
        myNV=myTCP.getTournament().getNVal();
        ListModelCoach.add(0,"COACH'S NAME");
        ListModelCoach.add(1,"_______________________________________");
        ListModelTeam.add(0,"TEAM'S NAME");
        ListModelTeam.add(1,"_______________________________________");
        for(int i=2;i<34;i++){
            ListModelTeam.add(i," ");
            ListModelCoach.add(i," ");

        }
        System.out.println(myNV);

        new Clock(hostIPadress,port,myIPadress,myTCP,50,ListModelTeam,ListModelCoach,this,myTCP.getTournament().getNVal()).start();


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        START = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListTeam = new javax.swing.JList(ListModelTeam);
        jScrollPane1 = new javax.swing.JScrollPane();
        ListCoach = new javax.swing.JList(ListModelCoach);
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        START.setEnabled(false);
        START.setText("START");
        START.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STARTActionPerformed(evt);
            }
        });
        getContentPane().add(START, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, -1, -1));

        ListTeam.setFont(new java.awt.Font("DejaVu LGC Sans Condensed", 1, 14)); // NOI18N
        jScrollPane2.setViewportView(ListTeam);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 270, 400));

        ListCoach.setFont(new java.awt.Font("DejaVu LGC Sans Condensed", 1, 14)); // NOI18N
        jScrollPane1.setViewportView(ListCoach);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 270, 400));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IHMcoach/pelouse.jpg")));
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>                        
    /**
     *
     * Ce bouton lance la fenetre suivante quand tous les jouers sont deja crees
     */
    private void STARTActionPerformed(java.awt.event.ActionEvent evt) {                                      
        
        CH4 = new CH_4_TournoiPremierePhase(hostIPadress,port,myIPadress,myTCP);
        CH4.setVisible(true);
        //new liguapoulpe.Sound("/home/promo65/s.hababou/Desktop/Ligua Poulpe/Ligua Poulpe/src/Gorillaz-Soulchild.wav").start();
        this.setVisible(false);
    }                                     

    /**
     * Cette methode permettre utiliser le bouton "NEXT" quand tou les jouers sont pret
     */
    public void setButton(){
        START.setEnabled(true);
    }

    
    // Variables declaration - do not modify                     
    private javax.swing.JList ListCoach;
    private javax.swing.JList ListTeam;
    private javax.swing.JButton START;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration                   

}
