

package IHMcoach;
import Reseaux.*;
import liguapoulpe.*;

/**
 *
 * Cette classe affiche le resultat des matchs
 * @author Gus
 */
public class CH_7_MATCH extends javax.swing.JFrame {


    TCP_SERVER myTCP;
    private String hostIPadress, myIPadress;
    private int port;

    CH_4_TournoiPremierePhase CH4;
    CH_8_FinalPhase CH8;

    String typedumatch;

    ///////////////////////////////CONSTRUCTEUR SI ON VIENT DE LA//////////////////////
    ////////////////////////////PREMIERE PHASE/////////////////////////////////////
    public CH_7_MATCH(String hostIPadress,int port,String myIPadress,TCP_SERVER myTCP,CH_4_TournoiPremierePhase CH4,String typedumatch) {
        super("Match's end");
        initComponents();
        this.setSize(800, 600);
        this.setResizable(false);


        this.hostIPadress=hostIPadress;
        this.myIPadress=myIPadress;
        this.myTCP=myTCP;
        this.port=port;
        this.CH4 = CH4;
        this.typedumatch = typedumatch;
        typematch.setText(typedumatch);
        Tournament t=myTCP.getTournament();
        int myID=myTCP.getMyID();

        //On affiche les noms des equipes
        equipe1.setText(t.getIemeCoach(myID).getTeam().getName());
        equipe2.setText(t.getIemeCoach(myID).getTeam().getNextConcurrent().getName());

        //Si on est le serveur on lance le match
        if(hostIPadress==myIPadress){new TCP_CLIENT(hostIPadress,port,"nextRound:1").start();}
        liguapoulpe.Clock c = new liguapoulpe.Clock(1);
        c.start();
        while(c.getFlag()==false){}

        //On affiche le resultat du match
        t=myTCP.getTournament();
        String result1=String.valueOf(t.getIemeCoach(myID).getTeam().getLastWXFresults()[0]);
        String result2=String.valueOf(t.getIemeCoach(myID).getTeam().getLastWXFresults()[1]);

        buts1.setText(result1);
        buts2.setText(result2);
        
    }

    //////////////////////////////CONSTRUCTEUR SI ON VIENT DE LA//////////////////
    /////////////////////////////PHASE FINALE//////////////////////////////////////
    public CH_7_MATCH(String hostIPadress,int port,String myIPadress,TCP_SERVER myTCP,CH_8_FinalPhase CH8,String typedumatch) {
        super("Match's end");
        initComponents();
        this.setSize(800, 600);
        this.setResizable(false);


        this.hostIPadress=hostIPadress;
        this.myIPadress=myIPadress;
        this.myTCP=myTCP;
        this.port=port;


        Tournament t=myTCP.getTournament();
        int myID=myTCP.getMyID();


        this.CH8 = CH8;
        this.typedumatch = typedumatch;
        typematch.setText(typedumatch);

        //On affiche les noms des equipes
        equipe1.setText(t.getIemeCoach(myID).getTeam().getName());
        equipe2.setText(t.getIemeCoach(myID).getTeam().getNextConcurrent().getName());
        
        //Si on est le serveur on lance le match
        if(hostIPadress==myIPadress){new TCP_CLIENT(hostIPadress,port,"nextRound:1").start();}
        liguapoulpe.Clock c = new liguapoulpe.Clock(1);
        c.start();
        while(c.getFlag()==false){}

        t=myTCP.getTournament();

        //On affiche le resultat du match
        String result1=String.valueOf(t.getIemeCoach(myID).getTeam().getLastWXFresults()[0]);
        String result2=String.valueOf(t.getIemeCoach(myID).getTeam().getLastWXFresults()[1]);
        buts1.setText(result1);
        buts2.setText(result2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Next = new javax.swing.JButton();
        Game = new javax.swing.JLabel();
        typematch = new javax.swing.JTextField();
        equipe2 = new javax.swing.JTextField();
        equipe1 = new javax.swing.JTextField();
        buts1 = new javax.swing.JTextField();
        buts2 = new javax.swing.JTextField();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Next.setText("NEXT");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        getContentPane().add(Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 260, -1));

        Game.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IHMcoach/Game.jpg")));
        getContentPane().add(Game, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        typematch.setEditable(false);
        typematch.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
        typematch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        typematch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typematchActionPerformed(evt);
            }
        });
        getContentPane().add(typematch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 330, 60));

        equipe2.setEditable(false);
        equipe2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(equipe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 170, 50));

        equipe1.setEditable(false);
        equipe1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        equipe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipe1ActionPerformed(evt);
            }
        });
        getContentPane().add(equipe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 170, 50));

        buts1.setEditable(false);
        buts1.setFont(new java.awt.Font("DejaVu LGC Sans", 1, 18)); // NOI18N
        buts1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buts1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buts1ActionPerformed(evt);
            }
        });
        getContentPane().add(buts1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 170, 50));

        buts2.setEditable(false);
        buts2.setFont(new java.awt.Font("DejaVu LGC Sans", 1, 18)); // NOI18N
        buts2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(buts2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 170, 50));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IHMcoach/pelouse.jpg")));
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ce bouton retourne a la phase finale ou a la premiere phase
     */
    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        if (CH4 != null){
            CH4.setVisible(true);
            CH4.setRound();
            this.dispose();
        }
        else{
            CH8.setVisible(true);
            CH8.setRound();
            this.dispose();
        }
    }//GEN-LAST:event_NextActionPerformed

    private void equipe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipe1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equipe1ActionPerformed

    private void buts1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buts1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buts1ActionPerformed

    private void typematchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typematchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typematchActionPerformed

    /**
    * @param args the command line arguments
    */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Game;
    private javax.swing.JButton Next;
    private javax.swing.JTextField buts1;
    private javax.swing.JTextField buts2;
    private javax.swing.JTextField equipe1;
    private javax.swing.JTextField equipe2;
    private javax.swing.JTextField typematch;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables

}
