

package IHMcoach;

import Reseaux.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import liguapoulpe.*;

/**
 *
 * Cette classe affiche les noms et les resultats des equipes a la phase finale
 * @author Gus
 */
public class CH_8_FinalPhase extends javax.swing.JFrame {

    CH_5_Agenda CH5;
    CH_6_Coaching CH6;
    CH_7_MATCH CH7;
    CH_8_FinalPhase PhaseFinale;
    Tournament t;
    int nc;
    int n=0;

    //Variables de la partie reseau
    TCP_SERVER myTCP;
    private String hostIPadress, myIPadress;
    private int port;

    //ArrayLists pour l'affichage
    ArrayList<Team> temporal;
    ArrayList<Team> temporalA;
    ArrayList<Team> temporalB;
    ArrayList<Team> temporalC;
    ArrayList<Team> temporalD;

    Team team;

    ////////////////////////////////////////////////////
    ///////////////////MODELs//////////////////////////
    ///////////////////////////////////////////////////

    DefaultListModel GroupAModel = new DefaultListModel();
    DefaultListModel GroupBModel = new DefaultListModel();
    DefaultListModel GroupCModel = new DefaultListModel();
    DefaultListModel GroupDModel = new DefaultListModel();

    DefaultListModel QFNameModel1 = new DefaultListModel();
    DefaultListModel QFNameModel2 = new DefaultListModel();
    DefaultListModel QFNameModel3 = new DefaultListModel();
    DefaultListModel QFNameModel4 = new DefaultListModel();

    DefaultListModel SFNameModel1 = new DefaultListModel();
    DefaultListModel SFNameModel2 = new DefaultListModel();

    DefaultListModel FinalNameModel = new DefaultListModel();
    

    DefaultListModel QFScoreModel1 = new DefaultListModel();
    DefaultListModel QFScoreModel2 = new DefaultListModel();
    DefaultListModel QFScoreModel3 = new DefaultListModel();
    DefaultListModel QFScoreModel4 = new DefaultListModel();

    DefaultListModel SFScoreModel1 = new DefaultListModel();
    DefaultListModel SFScoreModel2 = new DefaultListModel();

    DefaultListModel FinalScoreModel = new DefaultListModel();
    


    /** Creates new form CoachPhaseFinale */
    public CH_8_FinalPhase(String hostIPadress,int port,String myIPadress,TCP_SERVER myTCP) {
        initComponents();
        this.setSize(800, 600);
        this.setResizable(false);
        this.myTCP=myTCP;
        this.hostIPadress=hostIPadress;
        this.myIPadress=myIPadress;
        this.myTCP=myTCP;
        this.port=port;
        this.t=myTCP.getTournament();
        this.nc = myTCP.getMyID();
        NextGame.setEnabled(false);
        ////////////////////////////////////////////////////////
        //////////////////////MODELs////////////////////////////
        ////////////////////////////////////////////////////////
        
        
        ////////////////////////////Groups//////////////////////
        
        for(int i = 0; i<4;i++){
            
            GroupAModel.add(i, t.getGroupA().getRanking()[i+1][0]);

        }
       
        for(int i = 0; i<4;i++){
            
            GroupBModel.add(i, t.getGroupB().getRanking()[i+1][0]);

        }
        
        for(int i = 0; i<4;i++){
            
            GroupCModel.add(i, t.getGroupC().getRanking()[i+1][0]);

        }
        
        for(int i = 0; i<4;i++){
            
            GroupDModel.add(i, t.getGroupD().getRanking()[i+1][0]);

        }

        /////////////////////QF///////////////////
        temporalA = t.getGroupQF().getTeams();
        for(int i = 0; i<2;i++){
            team = temporalA.get(i);
            QFNameModel1.add(i, team.getName());
            

        }
        
        for(int i = 2; i<4;i++){
            team = temporalA.get(i);
            QFNameModel2.add(i-2, team.getName());

        }
        
        for(int i = 4; i<6;i++){
            team = temporalA.get(i);
            QFNameModel3.add(i-4, team.getName());
        }
        temporalD = t.getGroupD().getTeams();
        for(int i = 6; i<8;i++){
            team = temporalA.get(i);
            QFNameModel4.add(i-6, team.getName());

        }

        ////////////////////SEMIFINALS/////////////////

        SFNameModel1.add(0,"semi-finalist -- 1");
        SFNameModel1.add(1,"semi-finalist -- 2");

        SFNameModel2.add(0,"semi-finalist -- 3");
        SFNameModel2.add(1,"semi-finalist -- 4");

        ////////////////FINALS////////////////////////

        FinalNameModel.add(0, "Finalist -- 1");
        FinalNameModel.add(1, "Finalist -- 2");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quarter1 = new javax.swing.JScrollPane();
        SF1_Score = new javax.swing.JList(SFScoreModel1);
        quarter2 = new javax.swing.JScrollPane();
        QF2_Name = new javax.swing.JList(QFNameModel2);
        quarter3 = new javax.swing.JScrollPane();
        QF3_Name = new javax.swing.JList(QFNameModel3);
        quarter4 = new javax.swing.JScrollPane();
        QF4_Name = new javax.swing.JList(QFNameModel4);
        finals = new javax.swing.JLabel();
        Coaching = new javax.swing.JButton();
        NextGame = new javax.swing.JButton();
        agenda = new javax.swing.JButton();
        Champion = new javax.swing.JLabel();
        ChampionsName = new javax.swing.JTextField();
        quarter5 = new javax.swing.JScrollPane();
        QF2_Score = new javax.swing.JList(QFScoreModel2);
        quarter6 = new javax.swing.JScrollPane();
        QF3_Score = new javax.swing.JList(QFScoreModel3);
        quarter7 = new javax.swing.JScrollPane();
        QF4_Score = new javax.swing.JList(QFScoreModel4);
        quarter8 = new javax.swing.JScrollPane();
        SF1_Name = new javax.swing.JList(SFNameModel1);
        quarter9 = new javax.swing.JScrollPane();
        SF2_Name = new javax.swing.JList(SFNameModel2);
        quarter10 = new javax.swing.JScrollPane();
        SF2_Score = new javax.swing.JList(SFScoreModel2);
        quarter11 = new javax.swing.JScrollPane();
        FINAL_Name = new javax.swing.JList(FinalNameModel);
        quarter12 = new javax.swing.JScrollPane();
        FINAL_SCORE = new javax.swing.JList(FinalScoreModel);
        quarter13 = new javax.swing.JScrollPane();
        QF1_Name = new javax.swing.JList(QFNameModel1);
        quarter14 = new javax.swing.JScrollPane();
        QF1_Score3 = new javax.swing.JList(QFScoreModel1);
        jScrollPane1 = new javax.swing.JScrollPane();
        GroupB = new javax.swing.JList(GroupBModel);
        jScrollPane2 = new javax.swing.JScrollPane();
        GroupC = new javax.swing.JList(GroupCModel);
        jScrollPane3 = new javax.swing.JScrollPane();
        GroupD = new javax.swing.JList(GroupDModel);
        jScrollPane4 = new javax.swing.JScrollPane();
        GroupA = new javax.swing.JList(GroupAModel);
        semifinals = new javax.swing.JLabel();
        quarterfinals = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SF1_Score.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        quarter1.setViewportView(SF1_Score);

        getContentPane().add(quarter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 50, 50));

        QF2_Name.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        quarter2.setViewportView(QF2_Name);

        getContentPane().add(quarter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 120, 50));

        QF3_Name.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        quarter3.setViewportView(QF3_Name);

        getContentPane().add(quarter3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 130, 50));

        QF4_Name.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        quarter4.setViewportView(QF4_Name);

        getContentPane().add(quarter4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 130, 50));

        finals.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        finals.setText("FINAL");
        getContentPane().add(finals, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        Coaching.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IHMcoach/Coaching.jpg")));
        Coaching.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoachingActionPerformed(evt);
            }
        });
        getContentPane().add(Coaching, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 250, 70));

        NextGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IHMcoach/NextGame.jpg")));
        NextGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextGameActionPerformed(evt);
            }
        });
        getContentPane().add(NextGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 300, 70));

        agenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IHMcoach/Agenda.jpg")));
        agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendaActionPerformed(evt);
            }
        });
        getContentPane().add(agenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 250, 70));

        Champion.setFont(new java.awt.Font("Comic Sans MS", 1, 18));
        Champion.setText("CHAMPION");
        getContentPane().add(Champion, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 120, 40));

        ChampionsName.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        ChampionsName.setText("CHAMPION");
        ChampionsName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChampionsNameActionPerformed(evt);
            }
        });
        getContentPane().add(ChampionsName, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 160, -1));

        QF2_Score.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        quarter5.setViewportView(QF2_Score);

        getContentPane().add(quarter5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 50, 50));

        QF3_Score.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        quarter6.setViewportView(QF3_Score);

        getContentPane().add(quarter6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 50, 50));

        QF4_Score.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        quarter7.setViewportView(QF4_Score);

        getContentPane().add(quarter7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 50, 50));

        SF1_Name.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        quarter8.setViewportView(SF1_Name);

        getContentPane().add(quarter8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 140, 50));

        SF2_Name.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        quarter9.setViewportView(SF2_Name);

        getContentPane().add(quarter9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 140, 50));

        SF2_Score.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        quarter10.setViewportView(SF2_Score);

        getContentPane().add(quarter10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 50, 50));

        FINAL_Name.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        quarter11.setViewportView(FINAL_Name);

        getContentPane().add(quarter11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 100, 50));

        FINAL_SCORE.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        quarter12.setViewportView(FINAL_SCORE);

        getContentPane().add(quarter12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 50, 50));

        QF1_Name.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        quarter13.setViewportView(QF1_Name);

        getContentPane().add(quarter13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 120, 50));

        QF1_Score3.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        quarter14.setViewportView(QF1_Score3);

        getContentPane().add(quarter14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 50, 50));

        GroupB.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jScrollPane1.setViewportView(GroupB);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 140, 90));

        GroupC.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jScrollPane2.setViewportView(GroupC);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 140, 90));

        GroupD.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jScrollPane3.setViewportView(GroupD);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 140, 90));

        GroupA.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jScrollPane4.setViewportView(GroupA);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 140, 90));

        semifinals.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        semifinals.setText("SEMI-FINALS");
        getContentPane().add(semifinals, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        quarterfinals.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        quarterfinals.setText("QUARTER FINALS");
        getContentPane().add(quarterfinals, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 140, 20));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IHMcoach/pelouse.jpg")));
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * Ce bouton lance l'agenda
     */
    private void agendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendaActionPerformed
        if(CH5 == null){
            CH5 = new CH_5_Agenda(hostIPadress,port,myIPadress,myTCP,this);
        }
        CH5.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_agendaActionPerformed

    /**
     *
     * Ce bouton lance la fenetre "Coaching"
     */
    private void CoachingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoachingActionPerformed
        int myID=myTCP.getMyID();

        new TCP_CLIENT(hostIPadress,port,"invalidateCoach:"+myID).start();
        CH6 = new CH_6_Coaching(hostIPadress,port,myID,myTCP,this);
        CH6.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CoachingActionPerformed

    /**
     *
     * Ce bouton lance le match suivante
     */
    private void NextGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextGameActionPerformed
            int myID=myTCP.getMyID();
            t=myTCP.getTournament();

          CH7 = new CH_7_MATCH(hostIPadress,port,myIPadress,myTCP,this,"Final Phase");
          CH7.setVisible(true);
          this.setVisible(false);


      
    }//GEN-LAST:event_NextGameActionPerformed

    private void ChampionsNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChampionsNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChampionsNameActionPerformed

    /**
    * @param args the command line arguments
    */

    /**
     * Cette methode grise tous les boutons si on est elimines
     */
    public void setEliminated(){
        NextGame.setEnabled(false);
        Coaching.setEnabled(false);
        agenda.setEnabled(false);

       
    }

    /**
     * Cette methode sert a griser et degriser les boutons quand on vient de
     * "Coaching"
     */
    public void getFlag(){
        NextGame.setEnabled(true);
        Coaching.setEnabled(false);
    }

    /**
     * Cette methode sert a afficher les noms et resultats des eauipes chaque match
     */
    public void setRound(){
        this.nc = myTCP.getMyID();
        Coaching.setEnabled(true);
        NextGame.setEnabled(false);
        n++;
        
        /////////////////////QF///////////////////
        if(n==1){
            temporalA = t.getGroupQF().getTeams();
            for(int i = 0; i<2;i++){
                team = temporalA.get(i);
                QFNameModel1.set(i, team.getName());
                QFScoreModel1.add(i,String.valueOf(team.getLastWXFresults()[0]));

            }

            for(int i = 2; i<4;i++){
                team = temporalA.get(i);
                QFNameModel2.set(i-2, team.getName());
                QFScoreModel2.add(i-2, String.valueOf(team.getLastWXFresults()[0]));
            }

            for(int i = 4; i<6;i++){
                team = temporalA.get(i);
                QFNameModel3.set(i-4, team.getName());
                QFScoreModel3.add(i-4, String.valueOf(team.getLastWXFresults()[0]));
            }
            temporalD = t.getGroupD().getTeams();
            for(int i = 6; i<8;i++){
                team = temporalA.get(i);
                QFNameModel4.set(i-6, team.getName());
                QFScoreModel4.add(i-6, String.valueOf(team.getLastWXFresults()[0]));
            }
        
            
        ////////////////////SEMIFINALS/////////////////
            temporalA = t.getGroupSF().getTeams();
            for(int i =0;i<2;i++){
                team = temporalA.get(i);
                SFNameModel1.set(i,team.getName());

            }
            for(int i=2;i<4;i++){
                team = temporalA.get(i);
                SFNameModel2.set(i-2,team.getName());

            }
            if(t.getIemeCoach(nc).getTeam().isGameOver()){ setEliminated();}
        }
         if(n==2){
            temporalA = t.getGroupSF().getTeams();
            for(int i =0;i<2;i++){
                team = temporalA.get(i);
                SFNameModel1.set(i,team.getName());
                SFScoreModel1.add(i, String.valueOf(team.getLastWXFresults()[0]));
            }
           
            for(int i=2;i<4;i++){
                team = temporalA.get(i);
                SFNameModel2.set(i-2,team.getName());
                SFScoreModel2.add(i-2, String.valueOf(team.getLastWXFresults()[0]));
            }



        ////////////////FINALS////////////////////////
            temporalA = t.getGroupF().getTeams();
            for(int i=0;i<2;i++){
                team = temporalA.get(i);
                FinalNameModel.set(i, team.getName());

            }
            if(t.getIemeCoach(nc).getTeam().isGameOver()){ setEliminated();}
        }
        if(n==3){
            temporalA = t.getGroupF().getTeams();
            for(int i=0;i<2;i++){
                team = temporalA.get(i);
                FinalScoreModel.add(i, String.valueOf(team.getLastWXFresults()[0]));

            }
            Team champion;
            for(int i=0;i<16;i++)
            {
              if(temporalA.get(i).isGameOver()==false)
              {
                champion=temporalA.get(i);
                ChampionsName.setText(champion.getName());
              }
            }
            
            setEliminated();// Cette methode grise le boutons quand le tournoi est fini
        }


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Champion;
    private javax.swing.JTextField ChampionsName;
    private javax.swing.JButton Coaching;
    private javax.swing.JList FINAL_Name;
    private javax.swing.JList FINAL_SCORE;
    private javax.swing.JList GroupA;
    private javax.swing.JList GroupB;
    private javax.swing.JList GroupC;
    private javax.swing.JList GroupD;
    private javax.swing.JButton NextGame;
    private javax.swing.JList QF1_Name;
    private javax.swing.JList QF1_Score3;
    private javax.swing.JList QF2_Name;
    private javax.swing.JList QF2_Score;
    private javax.swing.JList QF3_Name;
    private javax.swing.JList QF3_Score;
    private javax.swing.JList QF4_Name;
    private javax.swing.JList QF4_Score;
    private javax.swing.JList SF1_Name;
    private javax.swing.JList SF1_Score;
    private javax.swing.JList SF2_Name;
    private javax.swing.JList SF2_Score;
    private javax.swing.JButton agenda;
    private javax.swing.JLabel finals;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane quarter1;
    private javax.swing.JScrollPane quarter10;
    private javax.swing.JScrollPane quarter11;
    private javax.swing.JScrollPane quarter12;
    private javax.swing.JScrollPane quarter13;
    private javax.swing.JScrollPane quarter14;
    private javax.swing.JScrollPane quarter2;
    private javax.swing.JScrollPane quarter3;
    private javax.swing.JScrollPane quarter4;
    private javax.swing.JScrollPane quarter5;
    private javax.swing.JScrollPane quarter6;
    private javax.swing.JScrollPane quarter7;
    private javax.swing.JScrollPane quarter8;
    private javax.swing.JScrollPane quarter9;
    private javax.swing.JLabel quarterfinals;
    private javax.swing.JLabel semifinals;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables

}
